'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EditorEmpleado
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''registroId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registroId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtClaveEmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClaveEmp As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''calFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaIngreso As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtDomicilio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDomicilio As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtColonia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColonia As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtrfc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtrfc As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCiudad As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtCurp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurp As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbEstado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEstado As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtImss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImss As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtPais control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPais As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbTipoContrato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoContrato As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCp As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbPeriodicidadP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPeriodicidadP As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtTelefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefono As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPuesto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtCorreo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorreo As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRiesgo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbMetodoPago control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbMetodoPago As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''cmbTipoj control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoj As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtClabe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClabe As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbRegimen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbRegimen As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtNumCuenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumCuenta As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''cmbBanco control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBanco As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtSueldoDiario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSueldoDiario As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtAsimiladoTotalS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAsimiladoTotalS As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtFactorIntegracion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactorIntegracion As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtImptoCedular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImptoCedular As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtSueldoDiarioIntegrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSueldoDiarioIntegrado As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtDescansosxSemana control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescansosxSemana As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtPagoxHora control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPagoxHora As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtIntegradoTipo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIntegradoTipo As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtFactorComision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactorComision As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtPromCuotaV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPromCuotaV As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtFactorDestajo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFactorDestajo As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtPromedioPercepV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPromedioPercepV As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtHorasDia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHorasDia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
End Class
