'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GeneracionDeFiniquitosQuincenal
    
    '''<summary>
    '''conceptoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conceptoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''empleadoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empleadoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''contratoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contratoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblNoEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblAntiguedadDias control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAntiguedadDias As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNombreEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDiasLaboradosAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasLaboradosAnio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSueldoDiario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueldoDiario As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDiasVacacionesProporcionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasVacacionesProporcionales As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSueldoDiarioIntegrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueldoDiarioIntegrado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblVacacionesProporcionales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVacacionesProporcionales As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaIngreso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPorcentajePrimaVacacional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPorcentajePrimaVacacional As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaBaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaBaja As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPrimaVacacionalProporcional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrimaVacacionalProporcional As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDiasPagadosVacaciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiasPagadosVacaciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''lblDiasAguinaldoAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiasAguinaldoAnio As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPeriodo As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAguinaldoProporcional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAguinaldoProporcional As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbTipoFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTipoFiniquito As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAceptar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAceptar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''panelDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDatos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GridPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPercepciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''GridDeduciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDeduciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''txtPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercepciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtGravadoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravadoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtExentoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExentoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtDeducciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeducciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtNetoAPagar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetoAPagar As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rdoPercepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoPercepcion As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoDeducción control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoDeducción As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''cmbConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConcepto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''txtUnidadIncidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnidadIncidencia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtImporteIncidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImporteIncidencia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btnRegresar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRegresar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnGenerarFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerarFiniquito As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnDescargarPDFFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDescargarPDFFiniquito As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnDescargarPDFRenuncia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDescargarPDFRenuncia As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnConfirmarGeneraFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarGeneraFiniquito As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnConfirmarTimbraFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarTimbraFiniquito As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnEliminarConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEliminarConcepto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rwAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwAlerta As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwConfirmEliminaConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwConfirmEliminaConcepto As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwConfirmarGeneraFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwConfirmarGeneraFiniquito As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwConfirmarTimbraFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwConfirmarTimbraFiniquito As Global.Telerik.Web.UI.RadWindowManager
End Class
