'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModificacionNominaSemanalNormal
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''registroId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents registroId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtEjercicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEjercicio As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtNumPeriodo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPeriodo As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''calFechaInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaInt As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''calFechaFin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaFin As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtDia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''calFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents calFechaIngreso As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''txtNumEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumEmpleado As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtNombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombre As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuesto As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtRrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRrc As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtImssNom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImssNom As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtRegimencontrat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegimencontrat As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''txtCuotaDiaria1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCuotaDiaria1 As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtIMSS1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMSS1 As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''GridPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPercepciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''GridDeduciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDeduciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''txtPercepcione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercepcione As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtGravadISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravadISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtExentISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExentISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtDeduccione control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeduccione As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtNetoPagar1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetoPagar1 As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''cmbConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConcepto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAgregarC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarC As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''txtUnidad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnidad1 As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtImportes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImportes As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btnQuitarC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuitarC As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnModif control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModif As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnSalir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSalir As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnicon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnicon As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadButton1 As Global.Telerik.Web.UI.RadButton
End Class
