'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PTU
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''empleadoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empleadoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''contratoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents contratoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''empresaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents empresaId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ejercicioId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ejercicioId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''tiponominaId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tiponominaId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''conceptoId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents conceptoId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''GridPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPercepciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''GridDeduciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDeduciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''txtPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercepciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtGravadoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravadoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtExentoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExentoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtDeducciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeducciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtNetoAPagar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetoAPagar As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''rdoPercepcion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoPercepcion As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rdoDeducción control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdoDeducción As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''cmbConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbConcepto As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''txtUnidadIncidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnidadIncidencia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtImporteIncidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtImporteIncidencia As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btnEliminarConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEliminarConcepto As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''rwAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwAlerta As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwConfirmEliminaConcepto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwConfirmEliminaConcepto As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''RadAjaxLoadingPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxLoadingPanel1 As Global.Telerik.Web.UI.RadAjaxLoadingPanel
End Class
