'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class TimbrarFiniquito
    
    '''<summary>
    '''serie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents serie As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''folio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents folio As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblNoEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNoEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblNombreEmpleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNombreEmpleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSueldoDiario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueldoDiario As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSueldoDiarioIntegrado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSueldoDiarioIntegrado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaIngreso As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFechaBaja control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFechaBaja As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''panelDatos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelDatos As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''GridPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridPercepciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''GridDeduciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridDeduciones As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''txtPercepciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPercepciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtGravadoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGravadoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtExentoISR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExentoISR As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtDeducciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDeducciones As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''txtNetoAPagar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetoAPagar As Global.Telerik.Web.UI.RadNumericTextBox
    
    '''<summary>
    '''btnTimbrarFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTimbrarFiniquito As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''rwAlerta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwAlerta As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''rwConfirmTimbrarFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rwConfirmTimbrarFiniquito As Global.Telerik.Web.UI.RadWindowManager
    
    '''<summary>
    '''btnConfirmarTimbraFiniquito control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmarTimbraFiniquito As Global.System.Web.UI.WebControls.Button
End Class
